name: restaurant
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5

  http: ^0.13.5
  http_parser: ^4.0.2
  shared_preferences: ^2.1.1
  image_picker: ^0.8.0
  toast: ^0.3.0
  timeline_tile: 2.0.0
 
  provider: ^6.0.5
  page_indicator: ^0.4.1
  font_awesome_flutter: ^10.4.0
  path: ^1.8.1
 
  firebase_database: ^10.0.16
  firebase_storage: ^11.0.16
  flutter_keyboard_visibility_web:
 
  email_auth: ^1.0.0
  curved_navigation_bar: ^1.0.3
  get: ^4.6.5
  lottie: ^1.4.2
  introduction_screen: ^3.1.4
  animated_text_kit: ^4.2.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  url_launcher: ^6.1.10
  share: ^2.0.4
  flutter_launcher_icons: ^0.11.0
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  image_cropper: ^3.0.3
  google_maps_flutter: ^2.2.6
  google_maps_flutter_web: ^0.4.0+7
 
  
  
  
flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon.ico"
  # flutter_typeahead: any

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true
  # imagesAssets
  assets:
    - assets/empty_cart.png
    - assets/order_done.png
    - assets/riyal.png
    - images/logo2.jpg
    - assets/on_boarding_3.png

  # lottie files  
    - assets/lottie/animation_lkyl7hdq.json
    - assets/lottie/animation_lkyl9z10.json
    - assets/lottie/animation_lkyl32yx.json
    - assets/lottie/animation_lkyld16z.json

  
  fonts:
    - family: Al-Jazeera
      fonts:
        # - asset: assets/fonts/Al-Jazeera-Arabic-Bold.ttf
        - asset: assets/fonts/Al-Jazeera-Arabic-Light.ttf
        # - asset: assets/fonts/Al-Jazeera-Arabic-Regular.ttf
  